<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>MedPassport</title>';
echo '<style>';
echo '/* Basic styles */';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'background-color: #f4f4f4;';
echo '}';
echo 'header {';
echo 'background-color: #1194de;';
echo 'color: white;';
echo 'padding: 10px 0;';
echo 'text-align: center;';
echo '}';
echo 'nav {';
echo 'text-align: center;';
echo 'background-color: #444;';
echo 'padding: 10px;';
echo '}';
echo 'nav a {';
echo 'color: white;';
echo 'padding: 10px;';
echo 'text-decoration: none;';
echo 'font-size: 18px;';
echo '}';
echo 'nav a:hover {';
echo 'background-color: #555;';
echo '}';
echo '.container {';
echo 'padding: 20px;';
echo '}';
echo '.section {';
echo 'margin-bottom: 20px;';
echo '}';
echo 'footer {';
echo 'background-color: #333;';
echo 'color: white;';
echo 'text-align: center;';
echo 'padding: 10px 0;';
echo 'position: fixed;';
echo 'width: 100%;';
echo 'bottom: 0;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- Header -->';
echo '<header>';
echo '<h1>Welcome to MedPassport</h1>';
echo '</header>';
echo '';
echo '<!-- Navigation Bar -->';
echo '<nav>';
echo '<a href="http://localhost/php1/1.1.php">Home</a>';
echo '<a href="http://localhost/php1/1.3.php">About Us</a>';
echo '<a href="http://localhost/php1/Query.php">My Doctors</a>';
echo '<a href="http://localhost/php1/1.2.php">Help</a>';
echo '<a href="http://localhost/php1/1.8.php">Logout</a>';
echo '</nav>';
echo ';
echo ';
echo '<section id="contact" class="section">';
echo '<h2>Contact Us-</h2>';
echo '';
echo '';
echo '';
echo '<h3><span style="cursor: pointer; color: black;" onclick="showPopup()">MedPassport</span> :</h3>';
echo '';
echo '<ul>';
echo '<li>Support by Phone: 18958452XX</li>';
echo '<li>Support by Email: medpassport@gmail.com</li>';
echo '</ul>';
echo '';
echo '';
echo '';
echo '<h3>Premium MedPassport contacts :</h3>';
echo '';
echo '<li>Support by Phone: 18001166XX</li>';
echo '<li>Support by Email: medpassportseva@gmail.com</li>';
echo '';
echo '<p>';
echo '<h3>Address:</h3>';
echo '<li>For queries contact us: Manager, Imagine Marketing Limited Unit no. 202 & 203, 2nd floor, A-wing & B-wing, Corporate Avenue, Andheri Ghatkopar Link Road, Mumbai, Maharashtra-400093, India</li>';
echo '</p>';
echo '';
echo '<center><h3>Stay Connected</h3>';
echo '<a href="https://www.instagram.com/medpassport.in?igsh=MTk1eWR2N2tqeHB5Nw%3D%3D&utm_source=qr">';
echo '<img src="C:\Users\HARISH\Downloads\instagramm.png" width="48" height="48">';
echo '';
echo '<a href="https://www.facebook.com/share/RyDtoJixDwgnCScP/?mibextid=qi2Omg">';
echo '<img src="C:\Users\HARISH\Downloads\facebook.jpg" width="48" height="48">';
echo '';
echo '';
echo '</section>';
echo '';
echo '</div>';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>