<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>My Simple Website</title>';
echo '<style>';
echo '/* Basic styles */';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'background-color: #f4f4f4;';
echo '}';
echo 'header {';
echo 'background-color: #1194de;';
echo 'color: white;';
echo 'padding: 10px 0;';
echo 'text-align: center;';
echo '}';
echo 'nav {';
echo 'text-align: center;';
echo 'background-color: #444;';
echo 'padding: 10px;';
echo '}';
echo 'nav a {';
echo 'color: white;';
echo 'padding: 10px;';
echo 'text-decoration: none;';
echo 'font-size: 18px;';
echo '}';
echo 'nav a:hover {';
echo 'background-color: #555;';
echo '}';
echo '.container {';
echo 'padding: 20px;';
echo '}';
echo '.section {';
echo 'margin-bottom: 20px;';
echo '}';
echo 'footer {';
echo 'background-color: #333;';
echo 'color: white;';
echo 'text-align: center;';
echo 'padding: 10px 0;';
echo 'position: fixed;';
echo 'width: 100%;';
echo 'bottom: 0;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- Header -->';
echo '<header>';
echo '<h1>Welcome to MedPassport</h1>';
echo '</header>';
echo '';
echo '<!-- Navigation Bar -->';
echo '<nav>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/First.html">Home</a>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/About%20Us.html">About Us</a>';
echo '<a href="http://localhost/php1/Query.php">My Doctors</a>';
echo '<a href="http://localhost/php1/1.2.php">Help</a>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/Login%20Page.html">Logout</a>';
echo '</nav>';
echo '';
echo '<!-- About Section -->';
echo '<section id="about" class="section">';
echo '';
echo '<h2 style="text-align: center">About Us</h2>';
echo '<p>Welcome to Medpassport!';
echo '';
echo '<p>In a world that is increasingly interconnected, maintaining and sharing health credentials securely and efficiently is more important than ever. Our mission is to revolutionize the way individuals manage and present their health information on a global scale.';
echo '';
echo '<p>~Who We Are';
echo '';
echo '<p>At Medpassport, we are a dedicated team of healthcare professionals, technology experts, and global health advocates. Our diverse backgrounds allow us to approach the challenges of international health documentation with a unique blend of expertise and innovation.';
echo '';
echo '<p>~Our Mission';
echo '';
echo '<p>Our mission is to provide a seamless, secure, and user-friendly platform that allows individuals to manage their health records and vaccination status with ease. We strive to ensure that health information can be accessed, shared, and verified anywhere in the world, making international travel and global health management simpler and more reliable.';
echo '';
echo '<p>~What We Do';
echo '';
echo '<p>We offer a cutting-edge digital health passport system that consolidates your health credentials into a single, easily accessible platform. Our services include:';
echo '';
echo '<p>Secure Health Records Management: Store and manage your health information safely, with encryption and robust security measures.';
echo 'Global Compliance: Ensure your health credentials meet international standards and requirements for travel, work, and study.';
echo 'Easy Access and Sharing: Quickly access and share your health information with healthcare providers, employers, or authorities as needed.';
echo 'User-Centric Design: Navigate our platform with ease, thanks to our intuitive interface designed with you in mind.';
echo 'Our Vision';
echo '';
echo '<p>We envision a world where health information barriers are eliminated, and individuals can move freely and confidently, knowing their health credentials are universally recognized and securely managed. Our goal is to be at the forefront of this transformation, driving innovation and setting new standards in digital health documentation.';
echo '';
echo '<p>~Why Choose Us?';
echo '';
echo '<p>Trust and Security: We prioritize the protection of your personal health data with state-of-the-art security protocols.';
echo 'Global Reach: Our platform is designed to meet the diverse needs of users across different countries and regions.';
echo 'Customer Support: Our dedicated support team is here to assist you with any questions or issues, ensuring a smooth experience.';
echo 'Join us in shaping the future of international health management. Together, we can make global health travel and communication more accessible, efficient, and secure.';
echo '';
echo '';
echo '<p>Thank you for choosing [Medpassport]. We look forward to serving you!';
echo '';
echo '</p>';
echo '';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>