<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Patient Information Form</title>';
echo '</head>';
echo '<body>';
echo '<h1>Patient Information Form</h1>';
echo '<form action="submit_patient_info.php" method="post">';
echo '<fieldset>';
echo '<legend>Primary Information</legend>';
echo '<label for="first_name">First Name:</label>';
echo '<input type="text" id="first_name" name="first_name" required><br><br>';
echo '';
echo '<label for="last_name">Last Name:</label>';
echo '<input type="text" id="last_name" name="last_name" required><br><br>';
echo '';
echo '<label for="dob">Date of Birth:</label>';
echo '<input type="date" id="dob" name="dob" required><br><br>';
echo '';
echo '<label for="email">Email:</label>';
echo '<input type="email" id="email" name="email" required><br><br>';
echo '</fieldset>';
echo '';
echo '<fieldset>';
echo '<legend>Health Information</legend>';
echo '<label for="blood_type">Blood Type:</label>';
echo '<input type="text" id="blood_type" name="blood_type" required><br><br>';
echo '';
echo '<label for="allergies">Allergies:</label>';
echo '<textarea id="allergies" name="allergies" rows="4" cols="50"></textarea><br><br>';
echo '';
echo '<label for="medications">Medications:</label>';
echo '<textarea id="medications" name="medications" rows="4" cols="50"></textarea><br><br>';
echo '';
echo '<label for="medical_conditions">Medical Conditions:</label>';
echo '<textarea id="medical_conditions" name="medical_conditions" rows="4" cols="50"></textarea><br><br>';
echo '</fieldset>';
echo '';
echo '<input type="submit" value="Submit">';
echo '</form>';
echo '</body>';
echo '</html>';
?>