<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>MEDPASSPORT</title>';
echo '<style>';
echo '/* Basic styles */';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'background-color: #f4f4f4;';
echo '}';
echo 'header {';
echo 'background-color: #1194de;';
echo 'color: white;';
echo 'padding: 10px 0;';
echo 'text-align: center;';
echo '}';
echo 'nav {';
echo 'text-align: center;';
echo 'background-color: #444;';
echo 'padding: 10px;';
echo '}';
echo 'nav a {';
echo 'color: white;';
echo 'padding: 10px;';
echo 'text-decoration: none;';
echo 'font-size: 18px;';
echo '}';
echo 'nav a:hover {';
echo 'background-color: #555;';
echo '}';
echo '.container {';
echo 'padding: 20px;';
echo '}';
echo '.section {';
echo 'margin-bottom: 20px;';
echo '}';
echo 'footer {';
echo 'background-color: #333;';
echo 'color: white;';
echo 'text-align: center;';
echo 'padding: 10px 0;';
echo 'position: fixed;';
echo 'width: 100%;';
echo 'bottom: 0;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- Header -->';
echo '<header>';
echo '<h1>Welcome to MedPassport</h1>';
echo '</header>';
echo '';
echo '<!-- Navigation Bar -->';
echo '<nav>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/First.html">Home</a>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/About%20Us.html">About Us</a>';
echo '<a href="#Help">Help</a>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/Login%20Page.html">Login</a>';
echo '</nav>';
echo '';
echo '<form style="text-align:center;">';
echo '<label for="username">Username:</label><br>';
echo '<input type="text" id="username" name="username"><br>';
echo '<label for="password">Password:</label><br>';
echo '<input type="password" id="password" name="password">';
echo '<p>';
echo '';
echo '<input type="submit" value="Login"  onclick=javascript.validate(test1.value,test2.value)>';
echo '';
echo '</form>';
echo '';
echo '<a href="register" style=" a: link{';
echo 'text-align: center;';
echo '}';
echo 'a:hover {';
echo 'color: red;';
echo 'background-color: transparent;';
echo 'text-decoration: underline;';
echo 'text-align: center;';
echo '}">New? Register Now</a>';
echo '</form>';
echo '';
echo '<! javascript>';
echo '<script language="javascript">';
echo 'function validate(text1,text2)';
echo '{';
echo 'if(text1==workshop && text2==workshop)';
echo 'load("file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/Logged%20Home.html");';
echo 'else';
echo '{';
echo 'load("fail.html");';
echo '}';
echo '}';
echo 'function load(url)';
echo '{';
echo 'location href=url;';
echo '}';
echo '';
echo '';
echo '';
echo '';
echo '</body>';
echo '</html>';
?>