<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>MEDPASSPORT</title>';
echo '<style>';
echo '/* Basic styles */';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'background-color: #f4f4f4;';
echo '}';
echo 'header {';
echo 'background-color: #1194de;';
echo 'color: white;';
echo 'padding: 10px 0;';
echo 'text-align: center;';
echo '}';
echo 'nav {';
echo 'text-align: center;';
echo 'background-color: #444;';
echo 'padding: 10px;';
echo '}';
echo 'nav a {';
echo 'color: white;';
echo 'padding: 10px;';
echo 'text-decoration: none;';
echo 'font-size: 18px;';
echo '}';
echo 'nav a:hover {';
echo 'background-color: #555;';
echo '}';
echo '.container {';
echo 'padding: 20px;';
echo '}';
echo '.section {';
echo 'margin-bottom: 20px;';
echo '}';
echo 'footer {';
echo 'background-color: #333;';
echo 'color: white;';
echo 'text-align: center;';
echo 'padding: 10px 0;';
echo 'position: fixed;';
echo 'width: 100%;';
echo 'bottom: 0;';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '';
echo '<!-- Header -->';
echo '<header>';
echo '<h1>Welcome to MedPassport</h1>';
echo '</header>';
echo '';
echo '<!-- Navigation Bar -->';
echo '<nav>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/First.html">Home</a>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/About%20Us%20WL.html">About Us</a>';
echo '<a href="MyDoctors">My Doctors</a>';
echo '<a href="#Help">Help</a>';
echo '<a href="file:///C:/Users/tirth/OneDrive/Desktop/Hackathon/Login%20Page.html">Logout</a>';
echo '</nav>';
echo '';
echo '<!-- Main Content -->';
echo '<div class="container">';
echo '';
echo '<!-- Home Section -->';
echo '<section id="home" class="section">';
echo '<h2>Home</h2>';
echo '<p>This is the home section of the website where you can include some introductory information.</p>';
echo '</section>';
echo '';
echo '<!-- About Section -->';
echo '<section id="about" class="section">';
echo '<h2>About</h2>';
echo '<p>Tell visitors about yourself or your website here. Provide a brief history or overview.</p>';
echo '</section>';
echo '';
echo '<!-- Services Section -->';
echo '<section id="services" class="section">';
echo '<h2>Services</h2>';
echo '<p>Describe the services or products you offer. You can list them here.</p>';
echo '</section>';
echo '';
echo '<!-- Contact Section -->';
echo '<section id="contact" class="section">';
echo '<h2>Contact</h2>';
echo '<p>Provide contact details or a form to let visitors get in touch with you.</p>';
echo '</section>';
echo '';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>